# CALLED BY: ragghost/surgeon/builders/__init__.py (BUILDERS registry) -> road.py (build stage); tested by tests/test_surgeon_modules.py
"""Build a working command-line tool -- the FIFTH output type and the first that is NOT a web page,
so "a wide variety of SOFTWARE and outputs" is proven with a genuinely different shape. Reads the
system's JSON data and emits a self-contained, dependency-free Python CLI (`tool.py`) with
list / get / count commands over the first collection found, plus a README. Nothing to serve.
"""
from __future__ import annotations

import json
import os

from .._common import find as _find, name_context

_DATA_CANDIDATES = ["products.json", "items.json", "orders.json", "data.json", "metrics.json"]




def _first_collection(ws):
    for cand in _DATA_CANDIDATES:
        p = _find(ws, cand)
        if not p:
            continue
        try:
            data = json.load(open(p, encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if isinstance(data, list) and data:
            return cand, data
        if isinstance(data, dict):
            for v in data.values():
                if isinstance(v, list) and v:
                    return cand, v
    return None, []


# The generated CLI. Kept as a template with the data baked in, so the shipped tool is standalone
# (no path back into the original system). {DATA} and {NAME} are filled at build time.
_TEMPLATE = '''#!/usr/bin/env python3
"""{NAME} -- a small command-line tool over {SRC}. Generated by ragghost. No dependencies.

    python3 tool.py count
    python3 tool.py list [--limit N]
    python3 tool.py get <index>
    python3 tool.py find <text>        # rows whose any field contains <text>
"""
import json, sys

DATA = {DATA}


def _rows():
    return DATA


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__); return 0
    cmd = argv[0]
    rows = _rows()
    if cmd == "count":
        print(len(rows)); return 0
    if cmd == "list":
        limit = int(argv[argv.index("--limit") + 1]) if "--limit" in argv else len(rows)
        for i, r in enumerate(rows[:limit]):
            print(i, json.dumps(r, ensure_ascii=False))
        return 0
    if cmd == "get":
        i = int(argv[1])
        if 0 <= i < len(rows):
            print(json.dumps(rows[i], indent=2, ensure_ascii=False)); return 0
        print("no such index", file=sys.stderr); return 1
    if cmd == "find":
        needle = " ".join(argv[1:]).lower()
        hits = [r for r in rows if needle in json.dumps(r, ensure_ascii=False).lower()]
        for r in hits:
            print(json.dumps(r, ensure_ascii=False))
        return 0
    print("unknown command %r (try --help)" % cmd, file=sys.stderr); return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
'''


def build(ws: str, scope, out_dir: str) -> dict:
    cfg_p = _find(ws, "config.json")
    name = scope.get("store_name") or "tool"
    try:
        cfg = json.load(open(cfg_p, encoding="utf-8")) if cfg_p else {}
        if isinstance(cfg, dict) and cfg.get("store_name"):
            name = cfg["store_name"]
    except json.JSONDecodeError:
        pass
    src, rows = _first_collection(ws)
    os.makedirs(out_dir, exist_ok=True)
    code = _TEMPLATE.replace("{NAME}", str(name)).replace("{SRC}", str(src or "no data")) \
                    .replace("{DATA}", json.dumps(rows, indent=0, ensure_ascii=False))
    with open(os.path.join(out_dir, "tool.py"), "w", encoding="utf-8") as fh:
        fh.write(code)
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as fh:
        fh.write("# %s CLI\n\nA standalone command-line tool over `%s` (%d records). No "
                 "dependencies.\n\n```\npython3 tool.py count\npython3 tool.py list --limit 5\n"
                 "python3 tool.py get 0\npython3 tool.py find <text>\n```\n"
                 % (name, src or "the system's data", len(rows)))
    return {"name": name, "source": src, "records": len(rows), "files": ["tool.py", "README.md"]}


def rubric(scope):
    def has_tool(o, c):
        return os.path.exists(os.path.join(o, "tool.py")), "tool.py present"

    def tool_compiles(o, c):
        p = os.path.join(o, "tool.py")
        if not os.path.exists(p):
            return False, "tool.py missing"
        try:
            compile(open(p, encoding="utf-8").read(), p, "exec")
            return True, "tool.py is valid Python"
        except SyntaxError as e:
            return False, "tool.py does not compile: %s" % e

    def has_commands(o, c):
        t = open(os.path.join(o, "tool.py"), encoding="utf-8").read() if os.path.exists(os.path.join(o, "tool.py")) else ""
        return all(k in t for k in ('"count"', '"list"', '"get"', '"find"')), "list/get/count/find implemented"

    return [("has-tool", has_tool), ("tool-compiles", tool_compiles), ("has-commands", has_commands)]


grade_context = name_context("name", "tool")
